site_name: Artinet SDK Documentation
site_url: https://the-artinet-project.github.io/artinet-wiki/
repo_url: https://github.com/the-artinet-project/artinet-sdk
repo_name: the-artinet-project/artinet-sdk
site_description: Documentation and API reference for the Artinet SDK - Agent2Agent Protocol Implementation

theme:
  name: material
  logo: images/artinet-logo.png
  favicon: images/artinet-logo.ico
  custom_dir: docs/overrides
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/the-artinet-project/artinet-sdk
      name: Artinet SDK on GitHub

nav:
  - Home: index.md
  - SDK:
    - Quickstart: sdk/quickstart.md
    - Core API: sdk/core.md
    - Examples: sdk/examples.md
  - Agents:
    - Quick Agents: agents/quick_agents.md
  - API Reference: 
    - API Reference: api/index.md
  - Contributing:
    - Code Documentation: contributing/code-documentation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

