site_name: Artinet Documentation
site_url: https://the-artinet-project.github.io/artinet-documentation/
use_directory_urls: false
repo_url: https://github.com/the-artinet-project/artinet-sdk
repo_name: the-artinet-project/artinet-sdk
site_description: Documentation and API reference for the Artinet SDK - Agent2Agent Protocol Implementation

theme:
  name: material
  logo: images/artinet-logo.png
  favicon: images/artinet-logo.ico
  custom_dir: docs/overrides
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/the-artinet-project/artinet-sdk
      name: Artinet SDK on GitHub

nav:
  - Home: index.md
  - Agent Creation:
    - Overview: agents/agent-creation.md
    - Test and Deploy: agents/test-and-deploy.md
    - The Grid: agents/grid-management.md
    - API Key Creation: agents/api-keys.md
    - Quick Agent Tool: agents/create-quick-agent.md
  - Advanced Development:
    - Quickstart: sdk/quickstart.md
    - Core: sdk/core.md
    - Examples:
      - Overview: sdk/examples/index.md
      - Basic Server: sdk/examples/basic-server.md
      - Basic Usage: sdk/examples/basic-usage.md
      - Code Deployment: sdk/examples/code-deployment.md
      - File Storage Client: sdk/examples/file-storage-client.md
      - File Storage Client (Continued): sdk/examples/file-storage-client-continued.md
      - File Storage Server: sdk/examples/file-storage-server.md
      - Streaming Updates: sdk/examples/streaming-updates.md
      - Task Resubscribe: sdk/examples/task-resubscribe.md
      - Task Wrapper: sdk/examples/task-wrapper.md
      - Nested Deployment: sdk/examples/nested-deployment.md
    - SDK Tests:
      - Overview: sdk/tests/index.md
      - A2A MCP: sdk/tests/a2a-mcp.test.md
      - A2A Protocol: sdk/tests/a2a-protocol.test.md
      - Bundler: sdk/tests/bundler.test.md
      - Client: sdk/tests/client.test.md
      - Common Errors: sdk/tests/common-errors.test.md
      - Deployment: sdk/tests/deployment.xx.md
      - File Storage: sdk/tests/file-storage.test.md
      - HTTP Utils: sdk/tests/http-utils.test.md
      - Integration: sdk/tests/integration.test.md
      - Register: sdk/tests/register.test.md
      - RPC Client: sdk/tests/rpc-client.test.md
      - Server: sdk/tests/server.test.md
      - Server Error Handling: sdk/tests/server-error-handling.test.md
      - Server Impl: sdk/tests/server-impl.test.md
      - Streaming: sdk/tests/streaming.test.md
  - API Reference:
    - Overview: api/index.md
    - A2AClient: api/client.md
    - A2AServer: api/server.md
    - Task Context: api/task-context.md
    - Agent Bundler: api/bundler.md
  - Version History: versions.md
  - Contributing:
    - Code Documentation: contributing/code-documentation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
